### ISSUE TITLE
publish for Scala 2.12.0-RC1?

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#174] opened 2016-09-20 20:24 UTC
perhaps useful, Adriaan's changes to make it work in the Scala 2.12 community build:
- https://github.com/adriaanm/util/commit/17625f46400dcc3b777168e47b8244f932372794 
- https://github.com/adriaanm/util/commit/2bb041a2a3bf9086066d52df3ee954c45c7c2d8b

**Comment by kevinoliver** [comment] 2016-09-20 20:28
Thanks @SethTisue. I'll see about getting those patches incorporated.

**Comment by kevinoliver** [comment] 2016-09-20 23:17
Ok so https://github.com/adriaanm/util/commit/17625f46400dcc3b777168e47b8244f932372794 got sorted out in https://github.com/twitter/util/commit/90f218014dfbd85bf3d7b91246dee98cfda01161

And a patch for https://github.com/adriaanm/util/commit/2bb041a2a3bf9086066d52df3ee954c45c7c2d8b is on its way.

Thanks again for the heads up.

**Comment by kevinoliver** [comment] 2016-09-21 17:21
Cool. The fix for https://github.com/adriaanm/util/commit/2bb041a2a3bf9086066d52df3ee954c45c7c2d8b just got merged internally and will get pushed to the `develop` branch this Monday. Thanks again.

**Comment by SethTisue** [comment] 2016-09-26 23:01
the Scala 2.12 community build now tracks your develop branch, as of https://github.com/scala/community-builds/pull/307

you might still like to publish artifacts for 2.12.0-RC1?

**Comment by kevinoliver** [comment] 2016-09-27 00:15
thanks!

@mosesn, looks like we should move to 2.12.0-RC1

**Comment by mosesn** [comment] 2016-09-27 04:54
👍  yeah, I'm hoping to get to it next week.  tried a couple weeks ago but some of our deps weren't publishing for it yet.

**Comment by mosesn** [comment] 2016-10-04 00:29
@SethTisue jsyk, right now we're blocked on upgrading scalatest to 3.x internally, since it looks like they've stopped publishing 2.x versions for 2.12.  If the migration is painful, we might lobby scalatest to temporarily start publishing 2.x versions again.

**Comment by SethTisue** [comment] 2016-10-31 17:41
> we might lobby scalatest

that might be easier now that Scala 2.12.0 JARs are on Maven Central

**Comment by stuhood** [comment] 2016-10-31 20:38
We've leaned in on the scalatest `3.x` upgrade, and are nearly finished there. Possibly this week.

**Comment by jvican** [comment] 2016-11-09 10:38
Looking forward to the release of twitter/util for 2.12.0.

**Comment by kevinoliver** [comment] 2016-11-11 23:39
@jcrossley and others have been working on this and it looks like it should be ready real soon now.

**Comment by SethTisue** [comment] 2016-11-17 00:27
over at https://github.com/scala/community-builds/pull/399 I'm seeing

```
[twitter-util] [info] ConfigTest:
[twitter-util] [info] Config
[twitter-util] [info] - should computed should delay evaluation
[twitter-util] [info] - should subclass can override indepedent var for use in dependent var
[twitter-util] [info]   should missingValues
[twitter-util] [info]   - should must return empty Seq when no values are missing
[twitter-util] [info]   - should must find top-level missing values
[twitter-util] [info]   - should must find top-level and nested missing values
[twitter-util] [info]   - should must find nested missing values in optional sub-configs *** FAILED ***
[twitter-util] [info]     List("$anonfun$new$16.w", "baz.w") did not equal List("baz.w") (ConfigTest.scala:84)
[twitter-util] [error] Failed tests:
[twitter-util] [error] 	com.twitter.util.ConfigTest
```

**Comment by mosesn** [comment] 2016-11-17 19:13
@SethTisue we haven't changed anything in Config in a very long time, so I'm a little suspicious.

**Comment by SethTisue** [comment] 2016-11-17 20:05
well, it's on 2.12?

**Comment by SethTisue** [comment] 2016-11-17 20:08
the specific nightly used was `2.12.1-371bc2c-nightly`. if you want to try it yourself locally, http://stackoverflow.com/q/40622878/86485

**Comment by vkostyukov** [comment] 2016-11-18 00:23
@SethTisue @mosesn I'll look into that. Let me try to reproduce that locally first.

**Comment by kevinoliver** [comment] 2016-12-01 22:45
ok i can reproduce this locally. added this to `Build.scala`:
```
  resolvers += "nightlies" at
    "https://scala-ci.typesafe.com/artifactory/scala-release-temp/"
  scalaVersion := "2.12.1-371bc2c-nightly"
  scalaBinaryVersion := "2.12"  // or "2.11"
```

And then run: 
```
$ ./sbt ++2.12.0 util-core/test
<snip>
[error] Failed: Total 1065, Failed 1, Errors 0, Passed 1064
[error] Failed tests:
[error] 	com.twitter.util.ConfigTest
[error] (util-core/test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by kevinoliver** [comment] 2016-12-05 17:41
@SethTisue i merged a workaround and hopefully that fixes it. 

i didn't spend long digging into the difference in the generated code between 2.11, as this `Config.missingValues` code is deprecated and not well maintained. hoping we can remove it in the not too distant future.

**Closed by kevinoliver** 2016-12-05 17:41 UTC
